development:
  adapter: postgresql
  encoding: utf8
  database: politickin_development
  pool: 5
  username: kbhattar
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: politickin_test
  pool: 5
  username: kbhattar
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: politickin_production
  pool: 5
  username: kbhattar
  password:
